//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmaderBazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserID
    {
        public int ID { get; set; }
        public string AccType { get; set; }
        public Nullable<int> LastID { get; set; }
    }
}
