//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Buyers = new HashSet<Buyer>();
            this.Products = new HashSet<Product>();
            this.Tokens = new HashSet<Token>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ID { get; set; }
        public string UID { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string AccType { get; set; }
        public string AccStatus { get; set; }
    
        public virtual ICollection<Buyer> Buyers { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
